metadata:
  description: config for RRFS_CONUScompact_13km, retro, on Hera
user:
  MACHINE: hera
  ACCOUNT: da-cpu
platform:
  WORKFLOW_MANAGER: rocoto
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: aqm_retro_conus_13km
  PREDEF_GRID_NAME: RRFS_CONUScompact_13km
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2020090112'
  DATE_LAST_CYCL:  '2020093012'
  INCR_CYCL_FREQ: 24
  FCST_LEN_HRS: 24
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  DEBUG: false
  COMPILER: intel
  DIAG_TABLE_TMPL_FN: diag_table_aqm.FV3_GFS_v16
  FIELD_TABLE_TMPL_FN: field_table_aqm.FV3_GFS_v16
  FIXlam: /scratch2/NCEPDEV/stmp3/Kai.Wang/expt_dirs/aqm_warm_aqmconus13_ML_IC_20221101-1101/fix_lam
  DO_REAL_TIME: false
  COLDSTART: false
  WARMSTART_CYCLE_DIR: /scratch1/NCEPDEV/stmp2/Hyundeok.Choi/cmaq/Kai/aqm_cold_aqmconus13_ML_IC_20200816-0831/2020083112
nco:
  envir_dfv: prod
  NET_dfv: aqm
  model_ver_dfv: v7.0
  RUN_dfv: aqm
#  OPSROOT_dfv: /path/to/custom/opsroot
  KEEPDATA_dfv: true
workflow_switches:
  RUN_TASK_MAKE_GRID: false
  RUN_TASK_MAKE_OROG: false
  RUN_TASK_MAKE_SFC_CLIMO: false
  RUN_TASK_GET_EXTRN_ICS: true
  RUN_TASK_GET_EXTRN_LBCS: true
  RUN_TASK_NEXUS_GFS_SFC: true
  RUN_TASK_RUN_POST: true #
  RUN_TASK_AQM_ICS: true
  RUN_TASK_AQM_LBCS: true
  RUN_TASK_NEXUS_EMISSION: true
  RUN_TASK_FIRE_EMISSION: true
  RUN_TASK_POINT_SOURCE: true
  RUN_TASK_PRE_POST_STAT: false
  RUN_TASK_POST_STAT_O3: false
  RUN_TASK_POST_STAT_PM25: false
  RUN_TASK_BIAS_CORRECTION_O3: false
  RUN_TASK_BIAS_CORRECTION_PM25: false
task_make_grid:
  GRID_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/RRFS_CONUScompact_13km
task_make_orog:
  OROG_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/RRFS_CONUScompact_13km
task_make_sfc_climo:
  SFC_CLIMO_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/RRFS_CONUScompact_13km
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: nemsio   #netcdf
  EXTRN_MDL_ICS_OFFSET_HRS: 0
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: nemsio   #netcdf
  EXTRN_MDL_LBCS_OFFSET_HRS: 0
  WTIME_GET_EXTRN_LBCS: 01:00:00
task_run_fcst:
  DT_ATMOS: 180
  LAYOUT_X: 33
  LAYOUT_Y: 8
  BLOCKSIZE: 29
  RESTART_INTERVAL: 24    #6 12 24
  WTIME_RUN_FCST: 04:00:00
  QUILTING: true
  PRINT_ESMF: false
  DO_FCST_RESTART: true
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: 775
  USE_CUSTOM_POST_CONFIG_FILE: false
task_aqm_lbcs:
  PPN_AQM_LBCS: 24
  WTIME_AQM_LBCS: 01:00:00
task_nexus_gfs_sfc:
  NEXUS_GFS_SFC_OFFSET_HRS: 0
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
  HALO_BLEND: 0
cpl_aqm_parm:
  CPL_AQM: true
  DO_AQM_CHEM_LBCS: true
  DO_AQM_GEFS_LBCS: true
  DO_AQM_DUST: true
  DO_AQM_CANOPY: false
  DO_AQM_PRODUCT: true
  DO_AQM_SAVE_AIRNOW_HIST: false
  DO_AQM_SAVE_FIRE: false
  AQM_BIO_FILE: BEIS_RRFScmaq_C775.ncf
  AQM_DUST_FILE_PREFIX: FENGSHA_p8_10km_inputs_CONUS_775
  AQM_DUST_FILE_SUFFIX: .nc
  AQM_CANOPY_FILE_PREFIX: gfs.t12z.geo
  AQM_CANOPY_FILE_SUFFIX: .canopy_regrid.nc
  AQM_FIRE_FILE_PREFIX: Hourly_Emissions_regrid_CONUS_13km
  AQM_FIRE_FILE_SUFFIX: _h72.nc
  AQM_RC_FIRE_FREQUENCY: hourly
  AQM_LBCS_FILES: gfs_bndy_chem_<MM>.tile7.000.nc      #am4_bndy.c793.2019<MM>.v1.nc
  COMINgefs: /scratch2/NCEPDEV/naqfc/Hyundeok.Choi/Data/GEFS_aerosol
  AQM_GEFS_FILE_PREFIX: gfs
  AQM_GEFS_FILE_CYC: 00
  NEXUS_GRID_FN: grid_spec_RRFS_CONUS_13km.nc       #grid_spec_793.nc
  NUM_SPLIT_NEXUS: 6
