metadata:
  description: This test is to ensure that the workflow running in community mode
    completes successfully on the RRFS_CONUS_25km grid using the GFS_v16 physics suite
    with ICs and LBCs derived from the FV3GFS.
user:
  RUN_ENVIR: community
  MACHINE: NOAACLOUD
  ACCOUNT: none
platform:
  BUILD_MOD_FN: build_noaacloud_intel
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 1
  EXPT_BASEDIR: /lustre/GST_test
  EXPT_SUBDIR: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2019061518'
  DATE_LAST_CYCL: '2019061518'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  DEBUG: false
  COMPILER: intel
task_make_grid:
  MAXTRIES_MAKE_GRID: 2
task_make_orog:
  MAXTRIES_MAKE_OROG: 2
task_make_sfc_climo:
  MAXTRIES_MAKE_SFC_CLIMO: 2
task_get_extrn_ics:
  MAXTRIES_GET_EXTRN_ICS: 1
  EXTRN_MDL_NAME_ICS: FV3GFS
  USE_USER_STAGED_EXTRN_FILES: true
  FV3GFS_FILE_FMT_ICS: grib2
  EXTRN_MDL_SOURCE_BASEDIR_ICS: /contrib/EPIC/UFS_SRW_App/v2p1/input_model_data/FV3GFS/grib2/${yyyymmddhh}
  EXTRN_MDL_FILES_ICS: []
  EXTRN_MDL_DATA_STORES: disk
task_get_extrn_lbcs:
  MAXTRIES_GET_EXTRN_LBCS: 1
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  USE_USER_STAGED_EXTRN_FILES: true
  FV3GFS_FILE_FMT_LBCS: grib2
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: /contrib/EPIC/UFS_SRW_App/v2p1/input_model_data/FV3GFS/grib2/${yyyymmddhh}
  EXTRN_MDL_FILES_LBCS: []
  EXTRN_MDL_DATA_STORES: disk
task_make_ics:
  MAXTRIES_MAKE_ICS: 2
task_make_lbcs:
  MAXTRIES_MAKE_LBCS: 2
task_run_fcst:
  MAXTRIES_RUN_FCST: 1
  PREDEF_GRID_NAME: RRFS_CONUS_25km
task_run_post:
  MAXTRIES_RUN_POST: 2
